### ISSUE TITLE
[HLS] Issue with video playback via Airplay

### ISSUE THREAD

**Issue by Sergeypro91** [muxinc/media-elements#17]
### Description of the issue
When trying to use Airplay on an iPhone, the function button available, but there is no video stream transmission to the receiving device, only the audio stream is sent. When playing full screen on iPhone, the native Airplay icon is also missing.

### Steps to reproduce
1. Open [HLS Video example](https://www.media-chrome.org/docs/en/media-elements/hls-video).
2. Add the Airplay tag to the example code.
```javascript
<media-controller>
  <hls-video
    src="https://stream.mux.com/A3VXy02VoUinw01pwyomEO3bHnG4P32xzV7u1j1FSzjNg.m3u8"
    slot="media"
    crossorigin
    muted
  ></hls-video>
  <media-loading-indicator slot="centered-chrome" noautohide></media-loading-indicator>
  <media-control-bar>
    <media-play-button></media-play-button>
    <media-seek-backward-button></media-seek-backward-button>
    <media-seek-forward-button ></media-seek-forward-button>
    <media-mute-button></media-mute-button>
    <media-volume-range></media-volume-range>
    <media-time-range></media-time-range>
    <media-time-display showduration remaining></media-time-display>
    <media-playback-rate-button></media-playback-rate-button>
    <media-fullscreen-button></media-fullscreen-button>
    <media-airplay-button></media-airplay-button>
  </media-control-bar>
</media-controller>
```
3. Click the Airplay button and select the device receiving the audio and video stream.

<img src="https://github.com/muxinc/media-elements/assets/5672678/71e2e731-a276-44d6-b72e-ffcf6a6b2257" width="350px">

4. Start playing the video.

<img src="https://github.com/muxinc/media-elements/assets/5672678/81a30875-6299-4770-9a0e-9a7fee9b8c0c" width="350px">

### Expected behavior
Audio and video are played on the device selected in the Airplay menu.

### Actual behavior
Only audio is played on the device selected in the Airplay menu, video continue playing on the mobile.

### System information
- media-chrome version: 3.2.2
- hls-video-element version: 1.2.2
- iOS: 17.4.1 / 17.5

**Comment by luwes** [comment]
thanks for reporting! I can reproduce this on Apple TV.

I'll look into this but I'm not sure what we can do about this because on iOS under the hood hls-video uses the native video tag with the raw m3u8 source URL.

**Comment by Sergeypro91** [comment]
As far as I understand, hls.js currently utilizes a new video streaming method called MMS (Managed Media Source) instead of MSE (Media Source Extensions).

Following [Apple's recommendations](https://webkit.org/blog/15036/how-to-use-media-source-extensions-with-airplay/), to enable AirPlay, you need to use source tags within the video tag, specifying the m3u8 playlist and the original video blob.

Below is the current working implementation of how it turned out to run:

```
import React, {
	DetailedHTMLProps,
	useCallback,
	useEffect,
	useRef,
	VideoHTMLAttributes,
} from 'react';
import { useMediaRef } from 'media-chrome/react/media-store';
import { Hls } from 'hls-video-element';

export type Info = Partial<MediaMetadata>;

export type Player = DetailedHTMLProps<
	VideoHTMLAttributes<HTMLVideoElement>,
	HTMLVideoElement
> &
	Info;

import style from './styles.module.css';

export const Video = (props: Player) => {
	const { src, crossOrigin, title, artist, album, artwork } = props;
	const mediaRefCallback = useMediaRef();
	const videoPlayerRef = useRef<HTMLVideoElement>(null);

	const runMediaSession = useCallback(() => {
		if ('mediaSession' in navigator) {
			navigator.mediaSession.metadata = new MediaMetadata({
				title,
				artist,
				album,
				artwork: artwork as MediaImage[],
			});
		}
	}, [album, artist, artwork, title]);

	const buildAirplayStream = useCallback(() => {
		const videoPlayerElement = videoPlayerRef.current;

		if (videoPlayerElement && Hls.isSupported() && src) {
			const hlsPlayer = new Hls();
			const hlsSource = document.createElement('source');
			const regularSource = document.createElement('source');

			mediaRefCallback(videoPlayerElement);
			hlsPlayer.loadSource(src);

			hlsSource.src = src;
			hlsSource.type = 'application/x-mpegURL';
			regularSource.type = 'video/mp4';
			videoPlayerElement.disableRemotePlayback = false;
			hlsPlayer.attachMedia(regularSource);
			videoPlayerElement.appendChild(hlsSource);
			videoPlayerElement.appendChild(regularSource);

			return hlsPlayer;
		} else if (
			src &&
			videoPlayerElement?.canPlayType('application/vnd.apple.mpegURL')
		) {
			videoPlayerElement.src = src;
		}
	}, [mediaRefCallback, src]);

	useEffect(() => {
		const hlsPlayer = buildAirplayStream();

		runMediaSession();

		return () => {
			if (hlsPlayer) {
				hlsPlayer.destroy();
			}
		};
	}, [buildAirplayStream, runMediaSession]);

	return (
		<hls-video
			ref={videoPlayerRef}
			className={style['video-player']}
			crossOrigin={crossOrigin}
		/>
	);
};

Video.displayName = 'Video';
```

This code is far from ideal, but I hope it will help someone save time searching for a working scheme for implementing Airplay.

**Comment by luwes** [comment]
good find! we'll implement this in hls-video soon
